# カタカナ15文字を自動識別するモデルの構築
# 課題投稿用Notebook
* これは課題投稿用ファイルです。
* このsubmit_katakana.ipynbファイルを編集し、学習済みモデルなどの必要ファイルを同じフォルダにおき、そのフォルダをzipしたものを投稿してください。

In [4]:
import numpy as np
import glob
import os,sys
import util
import pickle
from common.leNet import LeNet5

def makedataset():
    """
    データセットをつくる関数です。
    自由に編集してください。
    """
    
    # 次の行は変更しないこと
    test_data= util.loaddata()
    
    # 以下は自由に編集しても構いません
    # 必要な前処理をここに記述してください  
    
    # 正規化
#     test_data = test_data / test_data.max()
    test_data = test_data / 255.0
    test_data = test_data.astype('float32')

#     print(test_data.shape)
    
    # 配列形式変更
#     test_data = test_data.reshape(-1, 28*28)

    return test_data


def func_predict(test_data, test_label):
    """
    予測する関数
    data : 画像データ
    return loss, accuracy
    引数とreturn以外は、自由に編集してください    
    """
    
    # 以下を自由に編集してください
#     with open("best_model.pickle", "rb") as f:
#         model = pickle.load(f)
    
    pre_trained_params = np.load('pre-trained_model_params.npy', allow_pickle=True) 
    
    model = LeNet5()
    
    model.params = pre_trained_params
    
    accuracy = model.accuracy(test_data, test_label)
    loss  = model.loss(test_data, test_label)
    
    return loss, accuracy # 編集不可


def main():
    """
    編集しないでください。
    """
    # テスト用データをつくる
    test_data = makedataset()

    # 予測し精度を算出する
    util.accuracy(func_predict, test_data)
    
    return


if __name__=="__main__":
    main()

0
y is: [[5.82729164e-03 7.92485998e-03 4.19987061e-04 ... 5.65279129e-02
  4.22483230e-01 2.24485081e-02]
 [1.41470392e-03 3.21671901e-03 2.12271059e-04 ... 2.29231921e-02
  7.08567290e-01 8.69595131e-03]
 [2.13868344e-03 4.21992453e-03 4.13008982e-04 ... 3.68638138e-02
  5.30886234e-01 2.46006327e-02]
 ...
 [1.73050534e-03 1.06343152e-03 5.13675647e-04 ... 3.24152182e-02
  4.96036192e-01 1.40677464e-02]
 [1.32830072e-03 1.04838834e-03 3.56763481e-04 ... 3.31304714e-02
  4.39753310e-01 1.37253736e-02]
 [2.22089918e-03 1.66291867e-03 3.87821472e-04 ... 5.49920551e-02
  4.67006763e-01 1.36733998e-02]]
3.720954007260995 0.074
1
y is: [[0.002481   0.05347775 0.01049582 ... 0.03467318 0.3511658  0.00907484]
 [0.00674115 0.0693184  0.01879095 ... 0.05078117 0.26791185 0.00825455]
 [0.00311867 0.05647962 0.00508937 ... 0.04526407 0.12648152 0.00501399]
 ...
 [0.00584078 0.15467004 0.00780339 ... 0.07219235 0.26352164 0.01240346]
 [0.00335525 0.07046066 0.00835633 ... 0.03085479 0.13859237 0.

In [3]:
import numpy as np

pre_trained_params = np.load('pre-trained_model_params.npy', allow_pickle=True) 
    
pre_trained_params

array({'W1': array([[[[-0.0536322 , -0.22850068, -0.19371514, -0.45241636,
          -0.10330597],
         [-0.0180375 , -0.3155881 , -0.4237894 , -0.3584324 ,
          -0.20601457],
         [ 0.12027445,  0.21562687,  0.25756583,  0.0640741 ,
           0.293341  ],
         [ 0.27296972,  0.24322873,  0.4358493 ,  0.3865036 ,
           0.1238888 ],
         [-0.05107663,  0.22251698,  0.03404387,  0.19825216,
           0.2483199 ]]],


       [[[ 0.51669633,  0.4036465 ,  0.52576953,  0.60827166,
           0.01713442],
         [ 0.52112305,  0.43255463,  0.3115066 ,  0.33727753,
           0.44139037],
         [ 0.11234412,  0.22622786,  0.25039762,  0.1444803 ,
           0.29130816],
         [ 0.3422809 ,  0.13992211,  0.19031027, -0.07050087,
          -0.06153505],
         [ 0.22888865,  0.14201716, -0.03532305, -0.20998581,
          -0.6239851 ]]],


       [[[ 0.10344714,  0.11156794, -0.07170707, -0.2628198 ,
          -0.58317846],
         [ 0.36946967,  0.2396543

In [6]:
from common.leNet import LeNet5

model = LeNet5()

model.params = pre_trained_params

print(model.params['W1'])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices